name: Deploy Era 2026 Mothership (Keyless WIF)

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      target:
        description: 'Deployment target (corporate or verify)'
        required: true
        default: 'corporate'
        type: choice
        options: [corporate, verify]

jobs:
  deploy:
    name: Build and Deploy (Keyless)
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    env:
      TARGET: "${{ github.event.inputs.target || 'corporate' }}"
      PROJECT_ID: "rpr-corporate-site"
      # Mapping GitHub secrets + WIF (Quoted for diagnostic stability)
      RPR_PERPLEXITY_API_KEY: "${{ secrets.RPR_PERPLEXITY_API_KEY }}"
      RPR_NOTION_API_KEY: "${{ secrets.RPR_NOTION_API_KEY }}"
      RPR_GOOGLE_GENAI_KEY: "${{ secrets.RPR_GOOGLE_GENAI_KEY }}"
      RPR_FIREBASE_CONFIG: "${{ secrets.RPR_FIREBASE_CONFIG }}"
      RPR_GOOGLE_CLIENT_ID: "${{ secrets.RPR_GOOGLE_CLIENT_ID }}"
      RPR_NOTION_PAGE_ID: "${{ secrets.RPR_NOTION_PAGE_ID }}"

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Inject Environment Variables (GitHub secrets + WIF)
        run: node Scripts/configure-secrets.js

      - name: Install Validation Dependencies
        run: npm install --save-dev google-auth-library

      - name: Authenticate to Google Cloud (WIF v2)
        id: auth
        uses: google-github-actions/auth@v2
        with:
          # Authority: rpr-corporate-site (859831078276)
          workload_identity_provider: 'projects/859831078276/locations/global/workloadIdentityPools/github-pool/providers/github-provider'
          service_account: 'github-actions-deployer@rpr-corporate-site.iam.gserviceaccount.com'
          token_format: 'access_token'

      - name: Execute Pre-Deployment Functional Verification
        run: |
          chmod +x Scripts/ci-firebase-preflight.sh
          ./Scripts/ci-firebase-preflight.sh ${{ env.TARGET }}
        env:
          SA_JSON: "" # Enforce Keyless mode

      - name: Build Production Application
        run: npm run build

      - name: Firebase Hosting Deployment
        run: |
          npx firebase-tools deploy \
            --only hosting:${{ env.TARGET }} \
            --project ${{ env.PROJECT_ID }} \
            --token ${{ steps.auth.outputs.access_token }}