/**
 * /Users/puvansivanasan/PERPLEXITY-NEW/JOBS/2026-001-RPR-WEBSITE/RPR-REACT-MOTHERSHIP/Scripts/configure-secrets.js
 * Purpose: Inject environment variables into the Vite build substrate (ESM version).
 * Authority: TS-Λ3 | v1.1.7
 * Context: Harbor B (Mothership)
 */

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

// Re-establishing __dirname for ES Modules
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Target file is located in the root directory relative to this script
const targetPath = path.join(__dirname, '../.env');

/**
 * Authoritative list of environment variables required for the build.
 * RPR_NOTION_PAGE_ID is the canonical name for Harbor B.
 */
const secretKeys = [
  'RPR_PERPLEXITY_API_KEY',
  'RPR_NOTION_API_KEY',
  'RPR_GOOGLE_GENAI_KEY',
  'RPR_FIREBASE_CONFIG',
  'RPR_GOOGLE_CLIENT_ID',
  'RPR_NOTION_PAGE_ID'
];

console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
console.log('  INITIATING SECRET INJECTION (GitHub secrets + WIF)');
console.log('  Target Environment: Harbor B (Mothership)');
console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');

let envContent = '# GENERATED BY CONFIGURATION UTILITY (ESM)\n';
envContent += `# TIMESTAMP: ${new Date().toISOString()}\n\n`;

let latchedCount = 0;
let missingKeys = [];

secretKeys.forEach(key => {
  // Check for the value in process environment
  // Includes migration bridge for RPR_MYAUDIT_NOTION_PAGE_ID -> RPR_NOTION_PAGE_ID
  const value = process.env[key] || (key === 'RPR_NOTION_PAGE_ID' ? process.env.RPR_MYAUDIT_NOTION_PAGE_ID : null);
  
  if (value) {
    // Map RPR_ keys to VITE_ keys for Vite client-side access
    const viteKey = key.startsWith('RPR_') ? key.replace('RPR_', 'VITE_') : `VITE_${key}`;
    
    envContent += `${viteKey}="${value}"\n`;
    envContent += `${key}="${value}"\n`; // Maintain original key for node scripts
    
    console.log(`✅ [LATCHED] ${key} -> ${viteKey}`);
    latchedCount++;
  } else {
    console.log(`⚠️  [MISSING] ${key}`);
    missingKeys.push(key);
  }
});

try {
  fs.writeFileSync(targetPath, envContent);
  console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
  console.log(`  [SUCCESS] ${latchedCount} secrets injected into .env`);
  console.log(`  Target Path: ${targetPath}`);
  
  if (missingKeys.length > 0) {
    console.log('\n  ⚠️  STRIKE WARNING: Missing Infrastructure Fuel:');
    missingKeys.forEach(k => console.log(`     - ${k}`));
    console.log('  Action: Export these keys in your terminal and re-run.');
  }
  
  console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n');
} catch (error) {
  console.error(`\n❌ [FATAL] Failed to write configuration substrate: ${error.message}`);
  process.exit(1);
}